language: python

python:
  - 3.5

services:
  - docker

before_script:
  - pip install flake8

install:
  - docker-compose up --build -d
  - docker-compose run runserver sh -c "make build_sandbox"

script:
  - docker ps | grep -q djangoccstore
  - flake8 ccstore/
