# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 11:59
from __future__ import unicode_literals

import apps.core.util
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('cc', '0010_withdrawtransaction_walletconflicts'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_hash', models.CharField(max_length=64)),
                ('payment_request', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('complete', 'Complete'), ('expired', 'Expired'), ('error', 'Error')], default='pending_invoice', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=128, null=True)),
                ('satoshi_amount', models.IntegerField(blank=True, default=0)),
                ('coin_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default=apps.core.util.get_default_currency, max_length=12, verbose_name='Currency')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('complete', 'Complete'), ('expired', 'Expired'), ('error', 'Error')], default='pending_payment', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteProxyWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proxywallet', to='sites.Site')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProxyWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proxywallet', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
